name: "ssm"
version: "0.1.5"
usage: "AWS SSM parameter injection into Helm value files"
description: |-
  AWS SSM parameter injection in Helm value files
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-ssm"
hooks:
  install: "cd $HELM_PLUGIN_DIR/; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR/; ./scripts/install.sh"
