name: "ssm"
version: "0.1.6"
usage: "TODO"
description: |-
  AWS SSM parameter injection in Helm value files
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-ssm"
hooks:
  install: "cd $HELM_PLUGIN_DIR/; ./scripts/install.sh" # TODO
  update: "cd $HELM_PLUGIN_DIR/; ./scripts/install.sh"
