name: Build and Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Tag, Build, Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'
      - name: Build go binaries
        run: ./build.sh
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          draft: false
          prerelease: false
      - name: Upload release asset linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: helm-ssm-Linux-x86_64
          asset_name: helm-ssm_${{ steps.create_tag.outputs.new_tag }}_Linux_x86_64
          asset_content_type: application/octet-stream
      - name: Upload release asset macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: helm-ssm-Darwin-x86_64
          asset_name: helm-ssm_${{ steps.create_tag.outputs.new_tag }}_Darwin_x86_64
          asset_content_type: application/octet-stream
